from common.models import ModelResponse
from typing import Dict, Union
from ray.util import metrics


class NonExceptionThrowingCounter(metrics.Counter):
    def inc(self, value: Union[int, float] = 1.0, tags: Dict[str, str] = None):
        if value > 0:
            return super().inc(value, tags)


class Metrics:
    def __init__(self):
        self.requests_started = NonExceptionThrowingCounter(
            "aviary_requests_started",
            description="Number of requests started.",
            tag_keys=("model_id",),
        )
        self.requests_finished = NonExceptionThrowingCounter(
            "aviary_requests_finished",
            description="Number of requests finished",
            tag_keys=("model_id",),
        )
        self.requests_errored = NonExceptionThrowingCounter(
            "aviary_requests_errored",
            description="Number of requests errored",
            tag_keys=("model_id",),
        )

        self.tokens_generated = NonExceptionThrowingCounter(
            "aviary_tokens_generated",
            description="Number of tokens generated by Aviary",
            tag_keys=("model_id",),
        )
        self.tokens_input = NonExceptionThrowingCounter(
            "aviary_tokens_input",
            description="Number of tokens input by the user",
            tag_keys=("model_id",),
        )

    def track(self, res: ModelResponse, is_first_token: bool, model: str):
        model_tags = {"model_id": model}
        # Update metrics
        if res.num_generated_tokens:
            self.tokens_generated.inc(res.num_generated_tokens, tags=model_tags)
        if is_first_token and res.num_input_tokens:
            self.tokens_input.inc(res.num_input_tokens, tags=model_tags)

        if res.error:
            self.requests_errored.inc(tags=model_tags)

        if res.finish_reason is not None:
            self.requests_finished.inc(tags=model_tags)
