FROM vault.habana.ai/gaudi-docker/1.13.0/ubuntu20.04/habanalabs/pytorch-installer-2.1.0:latest
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home/user
RUN pip install lz4 numpy==1.24.4 tensorboard gpustat==1.0.0 sentencepiece accelerate datasets==2.12.0 gymnasium transformers dm-tree scikit-image peft
RUN pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
RUN pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.13.0
COPY pretrain/patch/hpu/0001-Init-megatron-deepspeed-with-Ray-cluster.patch .
COPY pretrain/patch/hpu/0002-Add-the-Huggingface-tokenizer.patch .
RUN git config --global user.email "root@example.com" 
RUN git config --global user.name "root" 
RUN git clone https://github.com/HabanaAI/Model-References.git && \
    cd Model-References && \
    git checkout -b ray bde21928ea8c295cd029fafe2cf737d50e715fe2 && \
    git am /home/user/0001-Init-megatron-deepspeed-with-Ray-cluster.patch && \
    git am /home/user/0002-Add-the-Huggingface-tokenizer.patch && \
    cd PyTorch/nlp/DeepSpeedExamples/Megatron-DeepSpeed/ && \
    pip install . 
# enable password-less ssh
RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
CMD ["sh", "-c", "service ssh restart; bash"]
