ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --ignore=E402, --ignore=E501, --ignore=E731, --ignore=F401]
        exclude: |
            (?x)^(
              examples/inference/vllm/ray-vllm-examples/llm.py|
              vllm-ext/vllm/extension/ns/__init__.py|
            )$


  # Black needs to be ran after ruff with --fix
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.981"
    hooks:
      - id: mypy
        exclude: |
          (?x)^(
            tests|
            vllm-ext/vllm/extension/ns/model/ns_loader.py|
            vllm-ext/vllm/extension/ns/kv_cache/ns_cache.py|
            vllm-ext/inference_engine/python/inference_engine/|
            vllm-ext/setup.py|
            examples/inference/vllm/ray-vllm-examples/llm.py|
            llm_on_ray/inference/inference_config.py|
            vllm-ext/vllm/extension/ns/
          )
        
        additional_dependencies:
          - mypy-extensions
          - pydantic==1.10.0
          - types-cachetools
          - types-filelock
          - types-PyYAML
          - types-redis
          - types-requests
          - types-paramiko
