ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --ignore=E402, --ignore=E501, --ignore=E731]

  # Black needs to be ran after ruff with --fix
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.950"
    hooks:
      - id: mypy
        exclude: tests
        additional_dependencies:
          - mypy-extensions
          - pydantic==1.10.0
          - types-cachetools
          - types-filelock
          - types-PyYAML
          - types-redis
          - types-requests
          - types-paramiko
