host: 0.0.0.0
port: 8000
name: default
route_prefix: null
num_replicas: 1
cpus_per_worker: 24
gpus_per_worker: 0
hpus_per_worker: 0
deepspeed: false
vllm:
  enabled: false
  precision: bf16
workers_per_group: 2
device: cpu
ipex:
  enabled: true
  precision: bf16
hpu_model_config:
  use_hpu_graphs: true
  torch_compile: false
  quant_config: null
model_description:
  model_id_or_path: null
  tokenizer_name_or_path: null
  config:
    trust_remote_code: false
    use_auth_token: null
    load_in_4bit: false
    torch_dtype: null
    revision: null
  prompt:
    intro: ''
    human_id: ''
    bot_id: ''
    stop_words: []
  chat_processor: null
  gpt_base_model: false
  quantized_model_id_or_path: null
  quantization_type: null
  peft_model_id_or_path: null
  peft_type: null
  ipexllm: false
  ipexllm_config:
    load_in_low_bit: ''
  input_processor: AutoProcessor
  model_loader: AutoModel
