FROM vault.habana.ai/gaudi-docker/1.13.0/ubuntu20.04/habanalabs/pytorch-installer-2.1.0:latest
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home/user
COPY pretrain/requirements.optimum-habana.txt /home/user/
RUN pip install -r requirements.optimum-habana.txt
RUN pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.13.0
RUN pip install --upgrade-strategy eager optimum[habana]
# enable password-less ssh
RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
CMD ["sh", "-c", "service ssh restart; bash"]