FROM nvcr.io/nvidia/pytorch:22.08-py3
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/user

COPY requirements.txt /home/user/
COPY pretrain/0001-workaround-and-hot-fix-for-llm-ray.patch /home/user/
RUN pip install -r requirements.txt
RUN pip install deepspeed lz4
RUN pip install -U numpy
ENV MAX_JOBS=32
RUN git clone https://github.com/microsoft/Megatron-DeepSpeed.git && \
    cd Megatron-DeepSpeed && \
    git checkout 319c9b1c9acd97016aa3f7b86f81b16b17bd61fe && \
    git am ../0001-workaround-and-hot-fix-for-llm-ray.patch && \
    pip install -e .
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    git checkout 22.04-dev &&\
    pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ && \
    python setup.py install
