FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    python-is-python3 \
    wget \
    git \
    build-essential \
    vim \
    htop \
    ssh \
    net-tools

WORKDIR /home/user

RUN pip install -U ray[default,data]
RUN pip install astunparse nltk gymnasium pyyaml datasets presidio_analyzer presidio_anonymizer 
RUN python -m spacy download en_core_web_lg

# enable password-less ssh
RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    sed -i 's/#   Port 22/Port 12345/' /etc/ssh/ssh_config && \
    sed -i 's/#Port 22/Port 12345/' /etc/ssh/sshd_config

CMD ["sh", "-c", "service ssh start; bash"]

