FROM nvcr.io/nvidia/pytorch:22.08-py3
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/user

COPY requirements.txt /home/user/
COPY pretrain/patch/gpu/0001-hot-fix-for-megatron-deepspeed.patch /home/user/
RUN pip install -r requirements.txt
RUN pip install deepspeed lz4
RUN pip install -U numpy
ENV MAX_JOBS=32
RUN cd src/megatron-core && \
    git am /home/user/0001-hot-fix-for-megatron-deepspeed.patch
RUN git config --global user.email "root@example.com" 
RUN git config --global user.name "root" 
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    git checkout 22.04-dev &&\
    pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ && \
    python setup.py install
