General:
  trainer_type: "dpo"
  base_model: mosaicml/mpt-7b
  tokenizer_name: EleutherAI/gpt-neox-20b
  gpt_base_model: false
  output_dir: /tmp/llm-ray/output
  save_strategy: no
  config:
    trust_remote_code: false
    use_auth_token: null
  lora_config:
    task_type: CAUSAL_LM
    r: 8
    lora_alpha: 32
    lora_dropout: 0.1
  enable_gradient_checkpointing: false
Dataset:
  data_type: "intel_orca"
  train_file: examples/data/sample_dpo_data.jsonl
  validation_file: null
  validation_split_percentage: 5
Training:
  optimizer: adamw_torch
  batch_size: 2
  epochs: 1
  learning_rate: 1.0e-05
  lr_scheduler: linear
  weight_decay: 0.0
  mixed_precision: bf16
  device: cpu
  num_training_workers: 2
  resources_per_worker:
    CPU: 32
  accelerate_mode: DDP
  gradient_accumulation_steps: 1
  logging_steps: 10
  use_dpo: True
  beta: 0.1
